name: CI/CD Pipeline for Snowflake Deployment

on:
  push:
    branches:
      - dev 
    paths:
      - 'deploy/**'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    # Step 1: Checkout the GitHub repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python and install Snowflake CLI (snowsql)
    - name: Set up Python and install Snowflake CLI
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Snowflake credentials
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
 

    # Step 4: Run Snowflake SQL scripts from the repository
    - name: Run Snowflake SQL scripts
      run: |
        # Loop through the SQL files in the repository directory and run them
        for file in ./deploy/*.sql; do
          echo "Running $file on Snowflake..."
          snowsql -f $file
        done

    # Step 5: Post Deployment - Optional: Notify or alert via Slack, email, etc.
    - name: Notify deployment status
      if: success()
      run: echo "Snowflake deployment successful!"
      # Optionally: Add Slack or Email notification logic here

