name: CI/CD  python Pipeline for Snowflake Deployment

on:
  push:
    branches:
      - dev
    paths:
      - 'deploy/**'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python and install Snowflake Connector
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Snowflake Connector
      run: |
        python -m pip install --upgrade pip
        pip install snowflake-connector-python

    - name: Set up Snowflake credentials
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WH }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      run: |
        echo "[connections]" > ~/.snowsql/config
        echo "accountname = $SNOWFLAKE_ACCOUNT" >> ~/.snowsql/config
        echo "username = $SNOWFLAKE_USER" >> ~/.snowsql/config
        echo "password = $SNOWFLAKE_PASSWORD" >> ~/.snowsql/config
        echo "database = $SNOWFLAKE_DATABASE" >> ~/.snowsql/config
        echo "schema = $SNOWFLAKE_SCHEMA" >> ~/.snowsql/config
        echo "warehouse = $SNOWFLAKE_WAREHOUSE" >> ~/.snowsql/config
        echo "role = $SNOWFLAKE_ROLE" >> ~/.snowsql/config

    - name: Run Snowflake SQL scripts with Python
      run: |
        python -c "
        import snowflake.connector
        import os
        
        # Set Snowflake connection parameters
        conn = snowflake.connector.connect(
            user=os.getenv('SNOWFLAKE_USER'),
            password=os.getenv('SNOWFLAKE_PASSWORD'),
            account=os.getenv('SNOWFLAKE_ACCOUNT'),
            warehouse=os.getenv('SNOWFLAKE_WAREHOUSE'),
            database=os.getenv('SNOWFLAKE_DATABASE'),
            schema=os.getenv('SNOWFLAKE_SCHEMA'),
            role=os.getenv('SNOWFLAKE_ROLE')
        )
        
        # Execute each SQL file
        for file in os.listdir('./deploy'):
            if file.endswith('.sql'):
                with open(f'./deploy/{file}', 'r') as f:
                    sql = f.read()
                    cursor = conn.cursor()
                    cursor.execute(sql)
                    cursor.close()
        conn.close()
        "

    - name: Notify deployment status
      if: success()
      run: echo "Snowflake deployment successful!"
